[versions]
agp = "9.3.1"
kotlin = "2.2.10"

activity = "1.13.0"
appcompat = "1.8.0"
browser = "1.10.0"
coreKtx = "1.19.0"
material = "1.14.0"
splashscreen = "1.2.0"
webkit = "1.17.0"

[libraries]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
