package io.github.rastislavsk.solarcast.data

import android.content.Context
import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.booleanPreferencesKey
import androidx.datastore.preferences.core.doublePreferencesKey
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.emptyPreferences
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import io.github.rastislavsk.solarcast.model.clamp
import io.github.rastislavsk.solarcast.model.norm360
import io.github.rastislavsk.solarcast.ui.theme.Scheme
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map
import org.json.JSONArray
import org.json.JSONObject
import java.io.IOException
import kotlin.math.roundToInt

/** One string of panels: how many, how big, how steep, which way. */
data class PvString(
    val panels: Int,
    val wp: Double,
    val tilt: Double,
    val az: Double,
) {
    val kwp: Double get() = panels * wp / 1000.0
}

data class Config(
    val lat: Double? = null,
    val lon: Double? = null,
    val place: String = "",
    val placeSub: String = "",
    val tz: String = "auto",
    val strings: List<PvString> = emptyList(),
    val acLimit: Double = 10.0,
    val eff: Double = 0.88,
    val tempCoef: Double = -0.35,
    val elev: Double = 0.0,
    val scheme: Scheme = Scheme.TERRA,
    val dark: Boolean = true,
    /** True while the array was generated by the app and the user has not touched it. */
    val suggested: Boolean = false,
) {
    val hasPlace: Boolean get() = lat != null && lon != null
    val ready: Boolean get() = hasPlace && strings.isNotEmpty()
    val totalKwp: Double get() = strings.sumOf { it.kwp }
    val totalPanels: Int get() = strings.sumOf { it.panels }
}

/** Drops half-entered strings and normalises the rest, exactly as the page does. */
fun PvString.cleaned(): PvString? {
    if (!panels.toDouble().isFinite() || !wp.isFinite() || !tilt.isFinite() || !az.isFinite()) return null
    if (panels <= 0 || wp <= 0 || tilt < 0 || tilt > 90) return null
    return PvString(panels = panels, wp = wp, tilt = clamp(tilt, 0.0, 90.0), az = norm360(az))
}

private val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "solarcast")

/**
 * The saved system. The web app keeps this in localStorage under `solarcast-v1`;
 * here it is a DataStore, which is the same idea with the same scope — this
 * device only, nothing leaves it.
 */
class ConfigRepository(private val context: Context) {

    private object Keys {
        val lat = doublePreferencesKey("lat")
        val lon = doublePreferencesKey("lon")
        val place = stringPreferencesKey("place")
        val placeSub = stringPreferencesKey("placeSub")
        val tz = stringPreferencesKey("tz")
        val strings = stringPreferencesKey("strings")
        val acLimit = doublePreferencesKey("acLimit")
        val eff = doublePreferencesKey("eff")
        val tempCoef = doublePreferencesKey("tempCoef")
        val elev = doublePreferencesKey("elev")
        val scheme = stringPreferencesKey("scheme")
        val dark = booleanPreferencesKey("dark")
        val suggested = booleanPreferencesKey("suggested")
    }

    val config: Flow<Config> = context.dataStore.data
        .catch { cause ->
            // A corrupt store must not brick the app; start over instead.
            if (cause is IOException) emit(emptyPreferences()) else throw cause
        }
        .map { prefs ->
            val defaults = Config()
            Config(
                lat = prefs[Keys.lat],
                lon = prefs[Keys.lon],
                place = prefs[Keys.place] ?: defaults.place,
                placeSub = prefs[Keys.placeSub] ?: defaults.placeSub,
                tz = prefs[Keys.tz] ?: defaults.tz,
                strings = decodeStrings(prefs[Keys.strings]),
                acLimit = prefs[Keys.acLimit] ?: defaults.acLimit,
                eff = prefs[Keys.eff] ?: defaults.eff,
                tempCoef = prefs[Keys.tempCoef] ?: defaults.tempCoef,
                elev = prefs[Keys.elev] ?: defaults.elev,
                scheme = prefs[Keys.scheme]?.let { name ->
                    Scheme.entries.firstOrNull { it.name.equals(name, ignoreCase = true) }
                } ?: defaults.scheme,
                dark = prefs[Keys.dark] ?: defaults.dark,
                suggested = prefs[Keys.suggested] ?: defaults.suggested,
            )
        }

    suspend fun save(config: Config) {
        context.dataStore.edit { prefs ->
            config.lat?.let { prefs[Keys.lat] = it } ?: prefs.remove(Keys.lat)
            config.lon?.let { prefs[Keys.lon] = it } ?: prefs.remove(Keys.lon)
            prefs[Keys.place] = config.place
            prefs[Keys.placeSub] = config.placeSub
            prefs[Keys.tz] = config.tz
            prefs[Keys.strings] = encodeStrings(config.strings)
            prefs[Keys.acLimit] = config.acLimit
            prefs[Keys.eff] = config.eff
            prefs[Keys.tempCoef] = config.tempCoef
            prefs[Keys.elev] = config.elev
            prefs[Keys.scheme] = config.scheme.name
            prefs[Keys.dark] = config.dark
            prefs[Keys.suggested] = config.suggested
        }
    }

    /** Wipes everything. The language stays: the user must be able to read what comes next. */
    suspend fun eraseAll() {
        context.dataStore.edit { it.clear() }
    }

    private fun encodeStrings(strings: List<PvString>): String {
        val array = JSONArray()
        strings.forEach { s ->
            array.put(
                JSONObject()
                    .put("panels", s.panels)
                    .put("wp", s.wp)
                    .put("tilt", s.tilt)
                    .put("az", s.az),
            )
        }
        return array.toString()
    }

    private fun decodeStrings(raw: String?): List<PvString> {
        if (raw.isNullOrBlank()) return emptyList()
        return runCatching {
            val array = JSONArray(raw)
            (0 until array.length()).mapNotNull { i ->
                val o = array.optJSONObject(i) ?: return@mapNotNull null
                PvString(
                    panels = o.optDouble("panels", 0.0).roundToInt(),
                    wp = o.optDouble("wp", 0.0),
                    tilt = o.optDouble("tilt", Double.NaN),
                    az = o.optDouble("az", Double.NaN),
                ).cleaned()
            }
        }.getOrDefault(emptyList())
    }
}
